# Generated by Django 4.1 on 2022-09-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
    ]
