# Generated by Django 4.1 on 2022-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_articulos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
