# Generated by Django 4.1 on 2022-09-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_articulos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
